<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="Aljaz&#39;s portfolio">
	<meta name="author" content="ALjaz">
	<meta name="generator" content="Hugo 0.75.1" />
	<title>General Social Survey &middot; Aljaz</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Aljaz</strong> <span>Know Thyself</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/blogs">Blogs</a></li>
            
                <li><a href="/elements.html">Elements</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/blogs" class="button special fit">Get Started</a></li>
            
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>General Social Survey</h1>
                            </header>
                            
                                <span class="image main"><img src="/img/blogs/pic08.jpg" alt="" /></span>
                            
                            


<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>#Let&#39;s first read and change the data for the answers such as &quot;Don&#39;t know&quot;,&quot;No answer&quot;, &quot;Not applicable&quot;. We classified these kind of answers as &quot;NA&quot;

gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,&quot;No answer&quot;, &quot;Not applicable&quot;))

glimpse(gss)</code></pre>
<pre><code>## Rows: 2,867
## Columns: 7
## $ emailmin &lt;chr&gt; &quot;0&quot;, &quot;30&quot;, &quot;NA&quot;, &quot;10&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;,…
## $ emailhr  &lt;chr&gt; &quot;12&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;2&quot;, &quot;40&quot;, &quot;NA&quot;, &quot;0&quot;, &quot;NA&quot;, &quot;2&quot;,…
## $ snapchat &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;NA&quot;, &quot;No&quot;…
## $ instagrm &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;Yes&quot;, &quot;NA&quot;, &quot;Yes&quot;, &quot;NA&quot;, &quot;No…
## $ twitter  &lt;chr&gt; &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, &quot;NA&quot;, &quot;No&quot;, …
## $ sex      &lt;chr&gt; &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;Male&quot;…
## $ degree   &lt;chr&gt; &quot;Bachelor&quot;, &quot;High school&quot;, &quot;Bachelor&quot;, &quot;High school&quot;, &quot;Gradu…</code></pre>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li><p>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</p></li>
<li><p><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</p></li>
<li><p><code>sex</code>: Female - Male</p></li>
<li><p><code>degree</code>: highest education level attained</p></li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Can we estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016? Let’s find out</p>
<p>First, we create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</p>
<pre class="r"><code>#Create new variable

gss2 &lt;- gss %&gt;% 
  
  #create new column in the data set with the function mutate
  
mutate(snap_insta = case_when(snapchat == &quot;Yes&quot; ~ &quot;Yes&quot;, 
                              instagrm == &quot;Yes&quot; ~ &quot;Yes&quot;, is.na(snapchat) &amp; 
                                is.na(instagrm) ~ &quot;NA_character_&quot;,
                              snapchat == &quot;No&quot; &amp; instagrm == &quot;No&quot; ~ &quot;No&quot;))               </code></pre>
<p>Secondly, we calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</p>
<pre class="r"><code>proportion_users &lt;- gss2 %&gt;% 
  
  #filter out NAs with the function filter
  
  filter(!is.na(snap_insta)) %&gt;% 
  
  #summarise and create the proportion of yes
  
  summarise( 
    InstaSnap_Users = count(snap_insta == &quot;Yes&quot;),
    Non_Users = count(snap_insta == &quot;No&quot;),
    Proportion = InstaSnap_Users/ (InstaSnap_Users + Non_Users)
    )

#Print the reults
proportion_users</code></pre>
<pre><code>## # A tibble: 1 x 3
##   InstaSnap_Users Non_Users Proportion
##             &lt;int&gt;     &lt;int&gt;      &lt;dbl&gt;
## 1             514       858      0.375</code></pre>
<p>Proportion if people with snapchat or instagram is about 37.5%.</p>
<p><strong>Confidence intervals</strong></p>
<p>Using the CI formula for proportions, we construct 95% CIs for men and women who used either Snapchat or Instagram</p>
<pre class="r"><code> #Create new variable

proportion_users_gender &lt;- gss2 %&gt;% 
  
  #filter out NAs with the help of function filter
  
  filter(!is.na(snap_insta)) %&gt;% 
  
  #group by gender
  
  group_by(sex) %&gt;% 
  
  #use summarise function for the calculation of statistics
  
  summarise(
    InstaSnap_Users = count(snap_insta == &quot;Yes&quot;),
    Non_Users = count(snap_insta == &quot;No&quot;),
    Count = n(),
    Proportion = InstaSnap_Users/ (InstaSnap_Users + Non_Users)
    )

proportion_users_gender  # proportion - proportion_yes / count of original value</code></pre>
<pre><code>## # A tibble: 2 x 5
##   sex    InstaSnap_Users Non_Users Count Proportion
##   &lt;chr&gt;            &lt;int&gt;     &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
## 1 Female             322       447   769      0.419
## 2 Male               192       411   603      0.318</code></pre>
<pre class="r"><code>#With the new variable we can calculate our confidance interval
proportions_gender_ci &lt;- proportion_users_gender %&gt;% 
  summarise(
    proportion = Proportion,
    size = Count,
    SE = sqrt((proportion*(1-proportion))/size),
    tcritical = qt(0.975, size-1),
    lower_ci = proportion - tcritical*SE,
    upper_ci = proportion + tcritical*SE
  )

#Print results
proportions_gender_ci</code></pre>
<pre><code>## # A tibble: 2 x 6
##   proportion  size     SE tcritical lower_ci upper_ci
##        &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1      0.419   769 0.0178      1.96    0.384    0.454
## 2      0.318   603 0.0190      1.96    0.281    0.356</code></pre>
<p>The proportion of men who use snapchat or instagram seems to be of about 32%, whereas the proportion of men is 42%. The women’s confidence interval goes from 38.4% to 45.4%, whereas men’s interval goes from 28.1% to 35.6%.</p>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p><strong>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?</strong></p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascneding order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<p>First, we will turn <code>degree</code> from a character variable into a factor variable. We made sure that the order is the correct one and that levels are not sorted alphabetically which is what R by default does.</p>
<pre class="r"><code>#Turn degree character variable into degree factor variable with the help of the function mutate

factor_degree&lt;- gss %&gt;% 
  
  #Exclude NAs
  na.omit(degree) %&gt;% 
  
  mutate(degree = factor(degree, 
                         levels = c(&quot;Lt high school&quot;, 
                                    &quot;High School&quot;, 
                                    &quot;Junior college&quot;, 
                                    &quot;Bachelor&quot;, 
                                    &quot;Graduate&quot;))) %&gt;% 
  #arrange in order
  arrange((degree))

#Print our new data set

factor_degree</code></pre>
<pre><code>## # A tibble: 2,867 x 7
##    emailmin emailhr snapchat instagrm twitter sex    degree        
##    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;fct&gt;         
##  1 30       0       No       No       No      Male   Lt high school
##  2 0        1       NA       NA       NA      Female Lt high school
##  3 NA       NA      No       Yes      No      Female Lt high school
##  4 0        1       Yes      Yes      No      Female Lt high school
##  5 NA       NA      NA       NA       NA      Female Lt high school
##  6 45       0       NA       NA       NA      Female Lt high school
##  7 NA       NA      No       Yes      No      Male   Lt high school
##  8 20       0       NA       NA       NA      Female Lt high school
##  9 NA       NA      NA       NA       NA      Female Lt high school
## 10 NA       NA      NA       NA       NA      Female Lt high school
## # … with 2,857 more rows</code></pre>
<p>Secondly, we create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in your new variable should also be NA.</p>
<pre class="r"><code>#Create new variable bachelor_graduate

bachelor_graduate &lt;-factor_degree%&gt;%
  mutate(bachelor_graduate = case_when(
    degree == &quot;Bachelor&quot; ~ &quot;Yes&quot;,
    degree == &quot;Graduate&quot; ~ &quot;Yes&quot;,
    degree != &quot;Graduate&quot;&amp; degree != &quot;Bachelor&quot; ~ &quot;No&quot;,
    
    #Else
    
    TRUE ~ &quot;NA&quot;
  ))

#print results

print(bachelor_graduate)</code></pre>
<pre><code>## # A tibble: 2,867 x 8
##    emailmin emailhr snapchat instagrm twitter sex    degree     bachelor_gradua…
##    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;fct&gt;      &lt;chr&gt;           
##  1 30       0       No       No       No      Male   Lt high s… No              
##  2 0        1       NA       NA       NA      Female Lt high s… No              
##  3 NA       NA      No       Yes      No      Female Lt high s… No              
##  4 0        1       Yes      Yes      No      Female Lt high s… No              
##  5 NA       NA      NA       NA       NA      Female Lt high s… No              
##  6 45       0       NA       NA       NA      Female Lt high s… No              
##  7 NA       NA      No       Yes      No      Male   Lt high s… No              
##  8 20       0       NA       NA       NA      Female Lt high s… No              
##  9 NA       NA      NA       NA       NA      Female Lt high s… No              
## 10 NA       NA      NA       NA       NA      Female Lt high s… No              
## # … with 2,857 more rows</code></pre>
<p>Our data set is prepared.</p>
<p>In the next step we calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</p>
<pre class="r"><code>#Create new variable

proportion_twitter_bachelor_graduate &lt;- bachelor_graduate %&gt;%
  
  #Filter fot the bachelor_graduate who use twitter
  
  filter(bachelor_graduate ==&quot;Yes&quot;) %&gt;% 
  
  #count twitter users
  
  count(twitter)%&gt;% 
  
  #with the help of function pivot_wider we make the data set wider by increasing the number of columns
  
  pivot_wider(names_from=twitter , values_from=n) %&gt;% 
  
  #we calculate the proportions with the help of function mutate
  
  mutate(twitter_yes= Yes/(No+Yes), twitter_no= No/(Yes+No))

#print the results

print(proportion_twitter_bachelor_graduate)</code></pre>
<pre><code>## # A tibble: 1 x 5
##    `NA`    No   Yes twitter_yes twitter_no
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;       &lt;dbl&gt;      &lt;dbl&gt;
## 1   365   375   114       0.233      0.767</code></pre>
<p>We can see that the chance that people who attended bachelor programs or graduated do not use twitter is 76%, whereas 24% do use it.</p>
<p>Using the CI formula for proportions, we constructed two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</p>
<pre class="r"><code>confidence_interval_twitter_yes &lt;- proportion_twitter_bachelor_graduate %&gt;% 
  
  #95% confidence interval calculations for people who use twitter
  
  mutate(SE=sqrt((twitter_yes*(1-twitter_yes)/(Yes+No)))) %&gt;% 
  summarise(lower_95=twitter_yes-1.96*SE, upper_95=twitter_yes+1.96*SE) %&gt;% 
  summarise(CI_Yes_Twitter=c(lower_95,upper_95))

confidence_interval_twitter_yes</code></pre>
<pre><code>## # A tibble: 2 x 1
##   CI_Yes_Twitter
##            &lt;dbl&gt;
## 1          0.196
## 2          0.271</code></pre>
<pre class="r"><code>  #95% confidence interval calculations for people who use twitter

confidence_interval_twitter_no &lt;- proportion_twitter_bachelor_graduate %&gt;% 
  mutate(SE=sqrt((twitter_no*(1-twitter_no)/(Yes+No)))) %&gt;% 
  summarise(lower_95=twitter_no-1.96*SE, upper_95=twitter_no+1.96*SE) %&gt;% 
  summarise(CI_No_Twitter=c(lower_95,upper_95))

confidence_interval_twitter_no</code></pre>
<pre><code>## # A tibble: 2 x 1
##   CI_No_Twitter
##           &lt;dbl&gt;
## 1         0.729
## 2         0.804</code></pre>
<blockquote>
<p>Two Conidence Intervals do not overlap. That means that the difference between Bachelor graduates who use (YES) and do not use (NO) is statistically significant.</p>
</blockquote>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<p>First, we create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</p>
<pre class="r"><code>#new varible email

email &lt;- gss %&gt;%
  
  #with help of function mutate_at change variable to numeric
  
  mutate_at(vars(emailhr,emailmin), funs(as.numeric)) %&gt;% 
  
  #create new total time in minutes
  
  mutate(email=(emailhr*60)+emailmin) %&gt;% 
  
  #arrange in descending order
  
  arrange(desc(email))

#Print the new variable

email</code></pre>
<pre><code>## # A tibble: 2,867 x 8
##    emailmin emailhr snapchat instagrm twitter sex    degree         email
##       &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;          &lt;dbl&gt;
##  1        0     100 NA       NA       NA      Female High school     6000
##  2        0      90 NA       NA       NA      Male   High school     5400
##  3        0      75 NA       NA       NA      Female High school     4500
##  4        0      72 NA       NA       NA      Male   High school     4320
##  5        0      70 NA       NA       NA      Female Junior college  4200
##  6        0      70 NA       NA       NA      Female Junior college  4200
##  7        0      60 No       Yes      No      Female Bachelor        3600
##  8        0      60 No       Yes      No      Male   High school     3600
##  9        0      60 No       Yes      Yes     Female Bachelor        3600
## 10        0      60 NA       NA       NA      Female Graduate        3600
## # … with 2,857 more rows</code></pre>
<p>If we want to visualise the distribution of this new variable, we need to find the mean and the median number of minutes respondents spend on email weekly.</p>
<pre class="r"><code>#Let&#39;s do a summary of statistics

summary_email &lt;- email %&gt;%
  
  #clear NAs
   na.omit(email) %&gt;%
  
  #summarize function helps us to summarize data
  
  summarize(mean = mean(email), median = median(email)) 

#print the summary data
summary_email</code></pre>
<pre><code>## # A tibble: 1 x 2
##    mean median
##   &lt;dbl&gt;  &lt;dbl&gt;
## 1  417.    120</code></pre>
<pre class="r"><code>#Let&#39;s see how the density plot looks like

ggplot(email, aes(y=email)) +
  
  geom_boxplot()+
  scale_y_log10() +
  
  #add theme
  
  theme_bw()+
  
  #add title and name of axis and source
  labs(title=&quot;US Adults spend more than 100 Minutes on Emails a Week!&quot;,
       y=&quot;Email Minutes&quot;,
       caption=&quot;General Social Survey&quot;
       )</code></pre>
<p><img src="/blogs/blog6_files/figure-html/nap_email2-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Is the mean or the median a better measure of the typical amoung of time Americans spend on email weekly? Why?</p>
<p>Whenever a graph falls on a normal distribution, using the mean is a good choice. But if your data has extreme scores (such as the difference between a someone spends 6000 minutes and someone who spends 100 minutes at email a week), you will need to look at median, because we find a much more representative number for our data.</p>
<p>Using the <code>infer</code> package, we calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. We interpreted this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes).</p>
<pre class="r"><code>#donwload of the infer package
library(infer)

#calculation of the 95% bootstrap confidence interval

bootstrap_email_ci &lt;- email %&gt;% 
  specify(response = email) %&gt;% 
  generate(reps = 100, type=&quot;bootstrap&quot;) %&gt;% 
  calculate(stat = &quot;mean&quot;) %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;) %&gt;% 
  
  # transform from min into h + min as decimal
  
  mutate(lower_ci = lower_ci/60, upper_ci = upper_ci/60) 

bootstrap_email_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     6.40     7.47</code></pre>
<p>The confidence interval for the mean email usage in the population is between 6hrs 24min and 7hrs 28min. This seems like a reasonable interval given that the sample mean is 6hrs and 57min.</p>
<ol start="4" style="list-style-type: decimal">
<li>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</li>
</ol>
<p>If we were to increase the confidence level of the interval to 99%, then the range of the interval would increase. Increasing the confidence will increase the margin of error resulting in a wider interval. In general, the greater the confidence level, the greater the range between the high and low points in a confidence interval.</p>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://twitter.com/popisanlist" class="icon alt fa-twitter" target="_blank"><span class="label">Twitter</span></a></li>
                
                    <li><a href="https://www.facebook.com/profile.php?id=100002186499443" class="icon alt fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                
                    <li><a href="https://github.com/AljazSirocic" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="www.linkedin.com/in/aljazsirocic" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; London Business School</li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
